# Generated by Django 6.0.4 on 2026-04-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Введите ваше имя", max_length=100, verbose_name="Имя")),
                (
                    "phone",
                    models.CharField(
                        help_text="Введите номер телефона", max_length=20, verbose_name="Контактный телефон"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Введите ваше сообщение", null=True, verbose_name="Сообщение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["name"],
            },
        ),
    ]
