# Generated by Django 6.0.4 on 2026-04-25 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["-created_at"], "verbose_name": "Контакт", "verbose_name_plural": "Контакты"},
        ),
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="Дата отправки"
            ),
            preserve_default=False,
        ),
    ]
